
name: "Cloud Buildpack Build"

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

env:
  ART_MIDGARD_SERVER: midgard.pp.argonaut.live
  ART_FRONTEGG_SERVER: argonaut-pp.frontegg.com



jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Argonaut
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      - name: Fetch branch name
        shell: bash
        run: echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}
        id: get_branch_name
      - name: Get Short SHA
        id: get_sha
        run: echo ::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)
      - name: Download art
        run: |
          curl --silent https://github.com/argonautdev/public/releases/latest/download/art-linux -L -o art
          chmod +x ./art
          mv ./art /usr/local/bin/art
      - name: Configure art
        run: |
          art configure --key ${{ secrets.dev_ART_KEY }} --secret ${{ secrets.dev_ART_SECRET }}
          art app deploy -f .art/external.yaml --set argonaut.env="dev"  --set argonaut.region="us-east-2"  --set argonaut.cluster="dev"  --set argonaut.serviceType="external"
